CREATE TABLE OrienteeringUser
(
	Id BIGINT NOT NULL IDENTITY(1, 1),
	Login NVARCHAR(MAX),
	FirstName NVARCHAR(MAX),
	LastName NVARCHAR(MAX),
	Password NVARCHAR(MAX),
	Profil NVARCHAR(1),
	TeamId BIGINT,
	PRIMARY KEY(Id)
)